development:
  adapter: postgresql
  encoding: utf8
  database: cambio_store_development
  pool: 20
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: cambio_store_test
  pool: 20
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

production:
  url:  <%= ENV["MY_DATABASE"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 20 %>
